config/routes.rb
Rails.application.routes.draw do
  
root 'messages#inbox'
get '/inbox', to: 'messages#inbox'
get '/users/current', to: 'users#current'
get '/users/:user_id/messages' => 'messages#received_messages'
 get '/outbox', to: 'messages#sent_messages'
get '/users/:user_id/messages/sent', to: 'messages#sent_messages'


  resources :users, except: [:index, :show] do
    resources :messages, shallow: true
  end

  resource :session, only: [:new, :create, :destroy]

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :sender, class: User
  belongs_to :recipient, class: User

validates :read, :important, inclusion: {
  in: [true, false]
}

 validates :subject, :content, :sender_id, :recipient_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  #add .password, .passwords, .password_confirmation=
  #validations on .password, and if .password_confirmation is present will require it to match .password
  #Also adds: .authenticate which will check a plain password against the digest

  #.sent_messages looks in Message for all whose :sender_id is my id
  has_many :sent_messages, class_name: Message, foreign_key: :sender_id
  #.received_messages looks in Message for all whose :received_id is my id
  has_many :received_messages, class_name: Message, foreign_key: :recipient_id

  validates :username, :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
      return nil unless session[:session_token]
      @current_user ||= User.find_by(session_token: session[:session_token])
  end

 private

  def login!(user)
    session[:session_token] = make_token
    user.session_token = session[:session_token]
    user.save!
  end

  def logout!
    current_user.update(session_token: nil)
    session[:session_token] = make_token
  end

  def make_token
    return SecureRandom.urlsafe_base64
  end
  
  def require_current_user
    redirect_to new_session_url unless current_user
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
   before_action :require_current_user, only: :inbox
   before_action :user_is_current_user, only: [:index, :new, :create]

  def inbox
     @users = User.all
  end

  def received_messages
    #todo: swtich to this
  
    @messages = current_user.received_messages
    
    respond_to do |format|
      format.html  { render text: "Please go to .json"}
      format.json { render json: @messages.to_json(include: :sender) }
    end
  end

def sent_messages
  #this should reverse what index is rgiht now
  @messages = current_user.sent_messages
 
    respond_to do |format|
      format.html  { render text: "Please go to .json"}
      format.json { render json: @messages.to_json(include: :recipient) }
    end

end
 

  def create
    # Pry.start(binding)
    @message = current_user.sent_messages.create(message_params)

    respond_to do |format|
      format.html  { render text: "Please go to .json"}
      format.json { render json: @message.to_json(include: :sender ) } 
    end
  end


  private

   def message_params
     params.require(:message).permit(:recipient_id, :subject, :content, :important)
   end

  def user_is_current_user
     redirect_to user_messages_path(current_user) unless params[:user_id].to_i == current_user.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_current_user, only: :destroy
  def new
    #when we use form for @user, it will infer automatically to try to post to userss#create bec User.new has not persisted, yet. We'll need to override this.
    @user = User.new

  end

  def create
   #login user, thn redirect to content
    @user = User.find_by(username: session_params[:username])
       if @user && @user.authenticate(session_params[:password])
        login!(@user)

       redirect_to root_url
     else
      redirect_to new_session_url
     end

  end

  def destroy
    logout!

    redirect_to new_session_url
  end

  private

  def session_params
     @session_params ||= params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_is_current_user, only: [:edit, :update]
 

 def current

    respond_to do |format|
      format.json { render json: { 
        id: current_user.id,
        name: current_user.name,
        username: current_user.username
        }
       }
    end 
  end
 

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params)

    if @user.save
      redirect_to new_session_url
    else
      render :new
    end
  end

  def edit
   @user = current_user
  end

  def update
     @user = current_user

     if @user.authenticate(params[:user][:current_password])
      @user.update(password_params)

      redirect_to user_messages_url(@user)
    else
       render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :password, :password_confirmation);
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation);
  end
  
  def user_is_current_user
    user = User.find(params[:id])
     if current_user
      redirect_to user_messages_path(current_user) unless user == current_user
    else
      redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

   def current_id
    respond_to do |format|

      format.json { render json: { id: current_user.id } }
    end 
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freemail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
 <nav class="logged-in clearfix">
 	<div class="logo">Freemail</div>

 	<ul class= "clearfix">
 	 <li>
   <%= button_to "Log Out", session_url, method: "delete"%>
     </li>
     <li>
  <%= link_to "Change Password", edit_user_url(current_user)%>
   </li>
    <% if action_name != "inbox" %>
   <li>
  <%= link_to "Inbox", inbox_url(current_user) %>
  </li>
   <% end %>
 </ul>
</nav>

<% end %>
<%= yield %>

</body>
</html>

app/views/messages/inbox.html.erb
<main class="inbox clearfix">
  <nav>
    <ul id="navigation">
      <li data-method="get-received">Received</li>
      <li data-method="get-sent">Sent</li>
      <li data-method="compose">Compose</li>
    </ul>
 </nav>
  <section class="messages ">
     <h3 class="currentBox">Inbox</h3>
    <ul>


    </ul>
  </section>
</main>


  <form id="compose" class="clearfix">
     To: <select name="recipient_id">
      <% @users.each do |user| %>
       <option value="<%= user.id %>">
        <%= user.username %>
       </option>
      <% end %>
    </select>
     <label for="important">Important</label>
     <input type="checkbox" id="important" name="important" value="true">
     <div class="close-window">&times;</div>
  
    <input type="text" name="subject" placeholder="Subject">
    <textarea name="content"></textarea>
     <div id="send-message">Send Mail</div>
   
  </form>



<%= javascript_include_tag 'messages' %>

app/views/users/edit.html.erb
<main class="gateway">

<h1>Change your password</h1>

  <%= form_for @user do |f| %>

	 <%= password_field_tag "user[current_password]", nil, placeholder: "current password" %> 
	   <br/>
	 <%= f.password_field :password, placeholder: "new password" %>
	   <br/>
	 <%= f.password_field :password_confrimation, placeholder: "confirm new password" %>
	   <br/>
	 <%= f.submit "Update password" %>
  <% end %>

</main>

app/views/users/new.html.erb
<main class="gateway">

	<h1>Sign up for Freemail!</h1>

	<%= form_for @user do |f| %>

	 <%= f.text_field :username, placeholder: "desired username" %> @freemail.com
	   <br/>
	  <%= f.text_field :name, placeholder: "your name" %> 
	   <br/>
	   <%= f.password_field :password, placeholder: "password" %>
	   <br/>
	   <%= f.password_field :password_confrimation, placeholder: "confirm password" %>
	   <br/>
	   <%= f.submit "Sign up" %>
	<% end %>

</main>